import { app, BrowserWindow, ipcMain } from 'electron';
import { getStats, startTracking, stopTracking } from './core/trackerService';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function createWindow(): void {
  const win = new BrowserWindow({
    width: 400,
    height: 300,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
}

app.whenReady().then(() => {
  createWindow();
  startTracking();
});

app.on('before-quit', () => {
  stopTracking();
});

ipcMain.handle('get-stats', () => {
  return getStats();
});
